### ISSUE TITLE
babel-preset-es2015 is deprecated

### ISSUE THREAD

**Issue by ryuran** [MaxArt2501/share-this#19]
Hello,

I use this plugin as dependency in my project but I remove recently `babel-preset-es2015` because it is deprecated.

I replace it by `babel-preset-env` as recommended.

But import of `hightlight-share` fail without `babel-preset-es2015`

```
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./node_modules/share-this/src/core.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "…/node_modules/share-this"
    at …/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (…/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (…/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (…/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (…/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (…/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (…/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (…/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (…/node_modules/babel-loader/lib/index.js:50:20)
 @ ./app/Resources/assets/js/highlightshare.js 3:17-38
 @ ./app/Resources/assets/js/main.js
 @ multi ./app/Resources/assets/js/main.js
```

I use webpack and babel-loader.
Babel seems to read .babelrc file of your package because I try to import a file heriting of this babel config. But babel-preset-es2015 is not present.

I think you should remove your `.babelrc` file form the prod package.

**Comment by ryuran** [comment]
I fixed it with the `babelrc: false` option for webpack babel-loader.

```
{
    test: /(\.jsx|\.js|\.es6)$/,
    use: {
        loader: 'babel-loader',
        options: {
            babelrc: false,
            presets: [
                ['env', {
                    useBuiltIns: true
                }]
            ],
            plugins: [
                ['transform-strict-mode', {
                    'strict': true
                }]
            ]
        }
    }
}
```
